In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


Loading the Data Set

In [0]:
import h5py
import numpy as np

h5f=h5py.File('/content/drive/My Drive/Colab Notebooks/SVHN_single_grey1.h5','r')

#Loading trainning and Test data

x_train=h5f['X_train'][:]
y_train=h5f['y_train'][:]
x_test=h5f['X_test'][:]
y_test=h5f['y_test'][:]
x_val = h5f['X_val'][:]
y_val = h5f['y_val'][:]

#Closing the file
h5f.close()

In [3]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(42000, 32, 32)
(18000, 32, 32)
(42000,)
(18000,)


In [0]:
#Reshaping the data to predict in KNN
x_train1=x_train.reshape(x_train.shape[0],32*32)
x_test1=x_test.reshape(x_test.shape[0],32*32)

In [5]:
#Applyig KNN
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn.fit(x_train1,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [0]:
#Predection
y_pred = knn.predict(x_test1)


In [8]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.49016666666666664
              precision    recall  f1-score   support

           0       0.38      0.66      0.48      1814
           1       0.44      0.70      0.54      1828
           2       0.55      0.52      0.53      1803
           3       0.42      0.39      0.41      1719
           4       0.67      0.61      0.64      1812
           5       0.48      0.36      0.41      1768
           6       0.47      0.38      0.42      1832
           7       0.72      0.58      0.64      1808
           8       0.42      0.33      0.37      1812
           9       0.52      0.36      0.43      1804

    accuracy                           0.49     18000
   macro avg       0.51      0.49      0.49     18000
weighted avg       0.51      0.49      0.49     18000

[[1201   60   44   37   45   45  129   31  109  113]
 [ 125 1285   83   81   84   36   36   58   18   22]
 [ 126  252  932  115   44   44   28  128   69   65]
 [ 164  255  166  677   54  157   36   46   92   72]
 [ 148  2

In [12]:
#Using Neural networks

import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
y_train=keras.utils.to_categorical(y_train,10)
y_test=keras.utils.to_categorical(y_test,10)
y_val=keras.utils.to_categorical(y_val,10)

In [0]:
x_train2=x_train.reshape(x_train.shape[0],32,32,1).astype('float32')
x_test2=x_test.reshape(x_test.shape[0],32,32,1).astype('float32')
x_val2=x_val.reshape(x_val.shape[0],32,32,1).astype('float32')

In [0]:
#Normalizing the data
x_train2/=255
x_test2/=255
x_val2/=255

In [18]:
#Building a NN Model
model=Sequential()
model.add(keras.layers.Flatten(input_shape=(32,32,1)))
model.add(Dense(200,activation ='relu'))
model.add(Dense(100,activation ='relu'))
model.add(keras.layers.Dropout(0.25))
model.add(Dense(10,activation='softmax'))

W0727 20:52:39.731825 139681256216448 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0727 20:52:39.741523 139681256216448 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [19]:
#Compile
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

W0727 20:55:08.737809 139681256216448 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0727 20:55:08.763406 139681256216448 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [20]:
model.fit(x_train2,y_train, batch_size=64, epochs=10, 
              validation_data=(x_test2, y_test))

W0727 20:56:07.285664 139681256216448 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 42000 samples, validate on 18000 samples
Epoch 1/10
42000/42000 [==============================] - 6s 147us/step - loss: 2.2917 - acc: 0.1300 - val_loss: 2.2612 - val_acc: 0.1954
Epoch 2/10
42000/42000 [==============================] - 2s 52us/step - loss: 2.2337 - acc: 0.2057 - val_loss: 2.1863 - val_acc: 0.2932
Epoch 3/10
42000/42000 [==============================] - 2s 52us/step - loss: 2.1346 - acc: 0.2908 - val_loss: 2.0413 - val_acc: 0.4389
Epoch 4/10
42000/42000 [==============================] - 2s 52us/step - loss: 1.9803 - acc: 0.3693 - val_loss: 1.8772 - val_acc: 0.4343
Epoch 5/10
42000/42000 [==============================] - 2s 52us/step - loss: 1.8079 - acc: 0.4251 - val_loss: 1.6898 - val_acc: 0.5227
Epoch 6/10
42000/42000 [==============================] - 2s 52us/step - loss: 1.6562 - acc: 0.4779 - val_loss: 1.5634 - val_acc: 0.5287
Epoch 7/10
42000/42000 [==============================] - 2s 52us/step - loss: 1.5406 - acc: 0.5179 - val_loss: 1.5204 - val_ac

In [0]:
#Adding Batch normalizationa and decreacing learning rate

#Building a NN Model
model1=Sequential()
model1.add(keras.layers.Flatten(input_shape=(32,32,1)))
model1.add(Dense(200,activation ='relu'))
model1.add(Dense(100,activation ='relu'))
model1.add(Dense(50,activation ='relu'))
model1.add(keras.layers.normalization.BatchNormalization())
model1.add(Dense(10,activation='softmax'))

In [0]:
#Compile
model1.compile(loss='categorical_crossentropy',optimizer ='adam', metrics=['accuracy'])

In [68]:
model1.fit(x_train2,y_train, batch_size=64, epochs=10, 
              validation_data=(x_test2, y_test))

Train on 42000 samples, validate on 18000 samples
Epoch 1/10
42000/42000 [==============================] - 5s 122us/step - loss: 1.7165 - acc: 0.4159 - val_loss: 1.7012 - val_acc: 0.4416
Epoch 2/10
42000/42000 [==============================] - 4s 88us/step - loss: 1.2559 - acc: 0.6050 - val_loss: 1.2173 - val_acc: 0.6137
Epoch 3/10
42000/42000 [==============================] - 4s 88us/step - loss: 1.1376 - acc: 0.6419 - val_loss: 1.3341 - val_acc: 0.5857
Epoch 4/10
42000/42000 [==============================] - 4s 88us/step - loss: 1.0506 - acc: 0.6712 - val_loss: 1.1710 - val_acc: 0.6323
Epoch 5/10
42000/42000 [==============================] - 4s 88us/step - loss: 0.9986 - acc: 0.6884 - val_loss: 1.0766 - val_acc: 0.6618
Epoch 6/10
42000/42000 [==============================] - 4s 87us/step - loss: 0.9424 - acc: 0.7060 - val_loss: 1.0281 - val_acc: 0.6784
Epoch 7/10
42000/42000 [==============================] - 4s 89us/step - loss: 0.8954 - acc: 0.7205 - val_loss: 0.8444 - val_ac

In [71]:
#Validation
print(model1.evaluate(x_val2,y_val))

60000/60000 [==============================] - 3s 54us/step
[0.9072382532437643, 0.7186833333333333]


In [70]:
print(model.evaluate(x_val2,y_val))

60000/60000 [==============================] - 3s 56us/step
[1.25029364639918, 0.63395]


In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
y_pre=model1.predict(x_val2)

In [0]:
y_pre1=model1.predict(x_test2)

In [0]:
import numpy as np

target_result=np.argmax(y_pre,axis=1)
test_result=np.argmax(y_pre1,axis=1)



In [86]:
#validation report
print(classification_report(y_val,target_result))
print(confusion_matrix(y_val,target_result))

              precision    recall  f1-score   support

           0       0.78      0.70      0.74      6000
           1       0.76      0.77      0.77      6000
           2       0.83      0.74      0.79      6000
           3       0.79      0.63      0.70      6000
           4       0.85      0.76      0.80      6000
           5       0.81      0.60      0.69      6000
           6       0.52      0.80      0.63      6000
           7       0.78      0.81      0.80      6000
           8       0.56      0.69      0.62      6000
           9       0.71      0.69      0.70      6000

    accuracy                           0.72     60000
   macro avg       0.74      0.72      0.72     60000
weighted avg       0.74      0.72      0.72     60000

[[4196  125   42   80   68   26  825   78  324  236]
 [ 129 4646   67   89  155   30  309  282  184  109]
 [  42  156 4462  112   73   45  159  364  328  259]
 [  92  217  151 3782   73  422  222  211  650  180]
 [  98  201  112   69 4538   

In [87]:
#Test Report
print(classification_report(y_test,test_result))
print(confusion_matrix(y_test,test_result))

              precision    recall  f1-score   support

           0       0.77      0.69      0.73      1814
           1       0.76      0.76      0.76      1828
           2       0.82      0.72      0.76      1803
           3       0.77      0.63      0.69      1719
           4       0.83      0.75      0.79      1812
           5       0.79      0.59      0.67      1768
           6       0.52      0.79      0.63      1832
           7       0.77      0.80      0.79      1808
           8       0.56      0.68      0.61      1812
           9       0.70      0.67      0.69      1804

    accuracy                           0.71     18000
   macro avg       0.73      0.71      0.71     18000
weighted avg       0.73      0.71      0.71     18000

[[1255   36   13   22   29    4  234   31  108   82]
 [  39 1389   21   35   62    6   96   89   62   29]
 [  20   57 1294   34   25   22   33  114  105   99]
 [  31   59   42 1080   22  138   58   60  176   53]
 [  34   57   35   25 1362   

#KNN 


1.   Classifier takes no time to train, since all that is required is to store and possibly index the training data.
2.   Computational cost at test time, since classifying a test example requires a comparison to every single training example which took lots of time to Predict.

3.   Low Accuracy and lot of miss clasifications


#NN
1.Classifier takes time to train,but test result time is low.
2.   Accuracy is high compared to KNN











