### Load tensorflow

In [1]:
import tensorflow as tf

In [2]:
#Reset Default graph - Needed only for Jupyter notebook
tf.reset_default_graph()

### Collect Data

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('prices.csv')

### Check all columns in the dataset

In [5]:
data.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

### Drop columns `date` and  `symbol`

In [6]:
data.drop(['date','symbol'],axis=1,inplace=True)

In [7]:
data.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set

In [8]:
data1=data.iloc[:1000,:]

In [9]:
data1.shape

(1000, 5)

In [10]:
feature_set=data1.drop('close',axis=1)
target_set=data1['close']

### Divide the data into train and test sets

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(feature_set,target_set,test_size=0.3,random_state=1)

## Building the graph in tensorflow

1.Define input data placeholders

In [14]:
#input layer
x=tf.placeholder(shape=[None,4],dtype=tf.float32, name='x-input')
y_=tf.placeholder(shape=[None],dtype=tf.float32,name='y-input')

In [22]:
#Normalize the data
x_n = tf.nn.l2_normalize(x,1)

2.Define Weights and Bias

In [17]:
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

Instructions for updating:
Colocations handled automatically by placer.


3.Prediction

In [23]:
y=tf.add(tf.matmul(x_n,W),b,name='output')

4.Loss (Cost) Function [Mean square error]

In [24]:
loss=tf.reduce_mean(tf.square(y-y_),name='Loss')

5.GradientDescent Optimizer to minimize Loss [GradientDescentOptimizer]

In [25]:
train_op=tf.train.GradientDescentOptimizer(0.03).minimize(loss)

## Execute the Graph for 100 epochs and observe the loss

In [21]:
ses=tf.Session()

In [27]:
ses.run(tf.global_variables_initializer())
training_epochs = 100

In [29]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = ses.run([train_op,loss],feed_dict={x:x_train, y_:y_train})
    
    if epoch % 10 == 0:
        print ('Training loss at step: ', epoch, ' is ', train_loss)

Training loss at step:  0  is  3567.2136
Training loss at step:  10  is  3567.2144
Training loss at step:  20  is  3567.2144
Training loss at step:  30  is  3567.2144
Training loss at step:  40  is  3567.2144
Training loss at step:  50  is  3567.2144
Training loss at step:  60  is  3567.2144
Training loss at step:  70  is  3567.2144
Training loss at step:  80  is  3567.2144
Training loss at step:  90  is  3567.2144


### Get the shapes and values of W and b

Hint: Use sess.run(W) to get W.

In [30]:
ses.run(W)

array([[2.6560160e-03],
       [2.6320412e-03],
       [2.6763959e-03],
       [3.3293568e+01]], dtype=float32)

### Find the Absolute mean square loss difference between training and testing loss.

In [32]:
test_epochs=100

In [33]:
for epoch in range(test_epochs):
            
    #Calculate train_op and loss
    _, test_loss = ses.run([train_op,loss],feed_dict={x:x_test, y_:y_test})
    
    if epoch % 10 == 0:
        print ('Training loss at step: ', epoch, ' is ', test_loss)

Training loss at step:  0  is  3018.3816
Training loss at step:  10  is  3018.0173
Training loss at step:  20  is  3017.9883
Training loss at step:  30  is  3017.9846
Training loss at step:  40  is  3017.9827
Training loss at step:  50  is  3017.986
Training loss at step:  60  is  3017.9834
Training loss at step:  70  is  3017.986
Training loss at step:  80  is  3017.9868
Training loss at step:  90  is  3017.9868


In [34]:
diff=abs(train_loss-test_loss)
diff

549.22754

In [39]:
ses.close

<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x000001DFD60ECD68>>

### Linear Classification using Keras

### Building the simple Neural Network in Keras with one neuron in the dense hidden layer.
#### Use Mean square error as loss function and sgd as optimizer

In [40]:
#Initialize Sequential Graph (model)
model = tf.keras.models.Sequential()

#Normalize input data
model.add(tf.keras.layers.BatchNormalization(input_shape=(4,)))

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1,activation='softmax'))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse')

### Execute the model

In [41]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
700/700 [==============================] - 0s 276us/sample - loss: 7868.8898
Epoch 2/100
700/700 [==============================] - 0s 31us/sample - loss: 7868.8898
Epoch 3/100
700/700 [==============================] - 0s 40us/sample - loss: 7868.8899
Epoch 4/100
700/700 [==============================] - 0s 40us/sample - loss: 7868.8899
Epoch 5/100
700/700 [==============================] - 0s 47us/sample - loss: 7868.8898
Epoch 6/100
700/700 [==============================] - 0s 30us/sample - loss: 7868.8898
Epoch 7/100
700/700 [==============================] - 0s 49us/sample - loss: 7868.8900
Epoch 8/100
700/700 [==============================] - 0s 51us/sample - loss: 7868.8900
Epoch 9/100
700/700 [==============================] - 0s 35us/sample - loss: 7868.8899
Epoch 10/100
700/700 [==============================] - 0s 36us/sample - loss: 7868.8898
Epoch 11/100
700/700 [==============================] - 0s 40us/sample - loss: 7868.8899
Epoch 12/100
700/700 [=======

700/700 [==============================] - 0s 34us/sample - loss: 7868.8899
Epoch 94/100
700/700 [==============================] - 0s 29us/sample - loss: 7868.8899
Epoch 95/100
700/700 [==============================] - 0s 29us/sample - loss: 7868.8898
Epoch 96/100
700/700 [==============================] - 0s 29us/sample - loss: 7868.8899
Epoch 97/100
700/700 [==============================] - 0s 40us/sample - loss: 7868.8900
Epoch 98/100
700/700 [==============================] - 0s 33us/sample - loss: 7868.8897
Epoch 99/100
700/700 [==============================] - 0s 22us/sample - loss: 7868.8899
Epoch 100/100
700/700 [==============================] - 0s 45us/sample - loss: 7868.8898


### Classification using Keras 

### Load the given Iris data using pandas (Iris.csv)

In [63]:
dt=pd.read_csv('Iris.csv')
dt.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Splitting the data into feature set and target set

In [76]:
X=dt.drop(['Id','Species'],axis=1)
Y=dt['Species']

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [65]:
from sklearn import preprocessing

In [66]:
le=preprocessing.LabelEncoder()

In [77]:
Y_e=le.fit_transform(Y)

In [80]:
target=pd.DataFrame(Y_e)
target.head()

0
0  0
1  0
2  0
3  0
4  0

In [85]:
target1=pd.get_dummies(dt['Species'])

In [86]:
target1.head()

Iris-setosa  Iris-versicolor  Iris-virginica
0            1                0               0
1            1                0               0
2            1                0               0
3            1                0               0
4            1                0               0

In [87]:
target1.shape

(150, 3)

### Divide the dataset into Training and test (70:30)

In [88]:
x_train,x_test,y_train,y_test=train_test_split(X,target1,test_size=0.3)

### Model
Build the model with following layers: <br>
1. First dense layer with 10 neurons with input shape 4 (according to the feature set) <br>
2. Second Dense layer with 8 neurons <br>
3. Output layer with 3 neurons with softmax activation (output layer, 3 neurons as we have 3 classes) <br>
4. Use SGD and categorical_crossentropy loss 

In [91]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [92]:
model = Sequential()
#specifying activation functions
model.add(Dense(10, input_dim=4))
model.add(Dense(8))
model.add(Dense(3,activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

### Fitting the model and predicting 

In [93]:
model.fit(x_train,y_train, nb_epoch=20, batch_size=10,  verbose=2)

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/20
 - 0s - loss: 2.2051 - acc: 0.5714
Epoch 2/20
 - 0s - loss: 0.6997 - acc: 0.7429
Epoch 3/20
 - 0s - loss: 0.6440 - acc: 0.6667
Epoch 4/20
 - 0s - loss: 0.5924 - acc: 0.7810
Epoch 5/20
 - 0s - loss: 0.5543 - acc: 0.8000
Epoch 6/20
 - 0s - loss: 0.5322 - acc: 0.7905
Epoch 7/20
 - 0s - loss: 0.5273 - acc: 0.7810
Epoch 8/20
 - 0s - loss: 0.4990 - acc: 0.8571
Epoch 9/20
 - 0s - loss: 0.4763 - acc: 0.8667
Epoch 10/20
 - 0s - loss: 0.4683 - acc: 0.8000
Epoch 11/20
 - 0s - loss: 0.4442 - acc: 0.8571
Epoch 12/20
 - 0s - loss: 0.4298 - acc: 0.8857
Epoch 13/20
 - 0s - loss: 0.4053 - acc: 0.8381
Epoch 14/20
 - 0s - loss: 0.4137 - acc: 0.8762
Epoch 15/20
 - 0s - loss: 0.4093 - acc: 0.8381
Epoch 16/20
 - 0s - loss: 0.3925 - acc: 0.8762
Epoch 17/20
 - 0s - loss: 0.3862 - acc: 0.8667
Epoch 18/20
 - 0s - loss: 0.3675 - acc: 0.8857
Epoch 19/20
 - 0s - loss: 0.3611 - acc: 0.9048
Epoch 20/20
 - 0s - loss: 0.3469 - acc: 0.9143


In [94]:
Y_p=model.predict(x_test)

In [97]:
Y_p

array([[9.5759914e-04, 4.5843083e-01, 5.4061162e-01],
       [1.5564569e-03, 4.8079142e-01, 5.1765215e-01],
       [1.8009242e-02, 5.5528498e-01, 4.2670578e-01],
       [9.4928014e-01, 4.8487954e-02, 2.2318638e-03],
       [2.3421695e-02, 5.2758497e-01, 4.4899333e-01],
       [9.3645567e-01, 6.0785033e-02, 2.7592226e-03],
       [9.1818273e-03, 5.7022661e-01, 4.2059159e-01],
       [9.3297750e-01, 6.3501045e-02, 3.5214263e-03],
       [5.4927152e-03, 5.3909940e-01, 4.5540780e-01],
       [6.5353391e-04, 2.0663656e-01, 7.9270989e-01],
       [9.3452775e-01, 6.2724143e-02, 2.7481613e-03],
       [6.0619358e-03, 4.1192260e-01, 5.8201551e-01],
       [9.6172601e-01, 3.6865525e-02, 1.4084780e-03],
       [9.7903168e-01, 2.0029677e-02, 9.3858404e-04],
       [3.0571662e-02, 6.0378116e-01, 3.6564720e-01],
       [9.6505827e-01, 3.3328120e-02, 1.6135911e-03],
       [9.0498000e-01, 8.8259526e-02, 6.7604398e-03],
       [9.1511917e-01, 8.0001146e-02, 4.8796944e-03],
       [9.7517055e-01, 2.412

In [101]:
test_result=np.argmax(Y_p,axis=1)
test_result

array([2, 2, 1, 0, 1, 0, 1, 0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 2, 2,
       2, 1, 0, 2, 1, 2, 2, 1, 2, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 1, 2, 0,
       2], dtype=int64)

In [106]:
a=y_test.values

In [108]:
target_result=np.argmax(a,axis=1)
target_result

array([2, 2, 1, 0, 1, 0, 1, 0, 2, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 2, 2,
       2, 1, 0, 2, 1, 2, 2, 1, 2, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 1, 2, 0,
       2], dtype=int64)

In [99]:
import numpy as np

### Report Accuracy of the predicted values

In [95]:
from sklearn.metrics import accuracy_score

In [109]:
Accuracy=accuracy_score(target_result,test_result)
Accuracy

0.9777777777777777